### PR TITLE
Add vpp as a possible switch

### PR DESCRIPTION
**Pull request by GabrielGanne**
The integration is done using the python API, and presenting the vpp cli
to mininet via dpctl.

vpp import is left within the VPPSwitch class so that this does not
become a new dependency.

### CODE REVIEW

**Comment by lantz** [comment]
This is interesting. Usually the first-class switches are either a) OpenFlow switches or b) built into Linux (LinuxBridge, LinuxRouter.) Does VPP support OpenFlow?

**Comment by GabrielGanne** [comment]
No.
You can have a look at what is vpp here if you wish : https://wiki.fd.io/view/VPP/What_is_VPP%3F

I'm on holidays, and have an erratic connection at best, I'll be back in a few weeks to answer or fix your reviews.
Thanks.

**Comment by GabrielGanne** [comment]
Hi,

Following your question, I added a few comments and some links to VPP to explain what I was doing.
I hope this makes it clearer.

Regards,

**Comment by GabrielGanne** [comment]
closing this for lack of interest.

**Pull request closed without merging**
