### PR TITLE
UPDATE command made generic.

### PR DESCRIPTION
**Pull request by BhattiMarry**
Update command was hard-coded for debian or ubuntu based systems which was 'apt-get'. Setting an update variable accordingly solves this problem.

### CODE REVIEW

**Comment by khayamgondal** [comment]
Seems good idea. Could be merged to master.

**Comment by lantz** [comment]
This code is mostly obsolete - why do you think this is necessary since we only supplied kernels for debian anyway?

**Comment by BhattiMarry** [comment]
I was installing it on RHEL 7.2 and i am using it well. Nothing to do with the kernal types or versions. Simply directed the correct installation path among different distributions which this installation supports.

**Comment by lantz** [comment]
I propose removing the `kernel` routine from `install.sh` as it is obsolete?

**Comment by lantz** [comment]
I'll merge this for now but probably we should remove the `kernel` routine from `install.sh`.

**Pull request merged**
