### PR TITLE
Use https instead of git

### PR DESCRIPTION
**Pull request by sinhayash**
https works even behind firewalls as git port might be blocked

### CODE REVIEW

**Comment by sinhayash** [comment]
Other changes which are required have already been done in 312ed1a4a53135eaf3b446bd94e80ebeefa20b8c

**Comment by montj2** [comment]
@sinhayash Thank you. Hope this gets accepted soon. Went to submit my PR and found your fix!

**Comment by lantz** [comment]
This is the wrong thing to do. If git is blocked, your network sucks.

That being said, if you want to do this anyway to work around your broken network, the right approach is to use https as a fallback if git doesn't work. I've suggested this multiple times.

**Comment by lantz** [comment]
Closing this - the right approach is to use https as a fallback if git doesn't work.

**Pull request closed without merging**
