### PR TITLE
Use incremental utf-8 decoder for buffered reading

### PR DESCRIPTION
**Pull request by benfrankel**
Only tested on Python 3.

Renamed the argument `maxbytes` to `size` because `len` counts the number of characters in a Python 3 string, not the number of bytes.

EDIT: Relates to issue #890.

### CODE REVIEW

**Comment by lantz** [comment]
I made a couple of changes/additions - let me know what you think.

**Comment by benfrankel** [comment]
Ok, now I only have the minor concern that a partial multi-byte UTF-8 character at the end of a stream will be ignored instead of raising a UnicodeDecodeError. Do you think that behavior is acceptable?

**Comment by lantz** [comment]
Yes, I think ignoring a partial character at the end of the stream is fine.

**Comment by lantz** [comment]
If you want to flatten these into a single commit, I think we can merge it.

**Comment by lantz** [comment]
Great, thanks!

**Pull request merged**
